### ISSUE TITLE
'Harmony.log.txt' creation on desktop can't be disabled

### ISSUE THREAD

**Issue by BentoGambin** [gnivler/AutoPicker#2]
The txt is 14 MB. There is no option for logging in the mod's config. Thanks in advance.

**Comment by gnivler** [comment]
Thanks for reporting, it's been fixed though, iinm.  Maybe you were grabbing it from thunderstore which I haven't updated..lazy.  Nexusmods.com has the latest.

**Comment by gnivler** [comment]
Done.  It would be great you could get all the people you know using this
to give a thumbs up.  3k downloads + mod pack downloads and I have TWO.

Enjoy!

**Comment by BentoGambin** [comment]
Thank you so so much! Btw, don't feel bad about the thumbs up. Look at Bepinex every one has got to download it and it has 119 thumbs up...

**Comment by gnivler** [comment]
Haha, yeah.  Sounds about right!
